ALTER TABLE "research_package_items" ADD COLUMN "agent_held" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "research_package_items" DROP CONSTRAINT "research_package_items_held_consistent";--> statement-breakpoint
ALTER TABLE "research_package_items" ADD CONSTRAINT "research_package_items_held_consistent" CHECK ("research_package_items"."held" = ("research_package_items"."human_held" OR "research_package_items"."qa_held" OR "research_package_items"."agent_held"));--> statement-breakpoint
INSERT INTO "research_jobs" ("id", "central_title", "central_url", "focus_note", "origin", "priority", "sequence", "status", "claimed_by_run_id", "dedupe_key", "created_at", "updated_at")
SELECT
  'migjob-0008-' || e."pkg_id",
  e."central_label",
  NULL,
  'Auto-generated by migration 0008 to enforce one-package-per-job; reparented from job ' || e."job_id" || ' (v3 allowed multiple packages per job).',
  'returned_correction',
  0,
  (SELECT COALESCE(MAX("sequence"), 0) FROM "research_jobs") + e."rn_extra",
  'submitted',
  e."run_id",
  'migrated-0008:' || e."pkg_id",
  e."submitted_at",
  e."submitted_at"
FROM (
  SELECT
    "id" AS "pkg_id",
    "job_id",
    "run_id",
    "central_label",
    "submitted_at",
    row_number() OVER (PARTITION BY "job_id" ORDER BY "submitted_at" ASC, "id" ASC) AS "rn",
    row_number() OVER (ORDER BY "submitted_at" ASC, "id" ASC) AS "rn_extra"
  FROM "research_packages"
) e
WHERE e."rn" > 1;--> statement-breakpoint
UPDATE "research_packages" p
SET "job_id" = 'migjob-0008-' || p."id"
WHERE p."id" IN (
  SELECT "id" FROM (
    SELECT "id", row_number() OVER (PARTITION BY "job_id" ORDER BY "submitted_at" ASC, "id" ASC) AS "rn"
    FROM "research_packages"
  ) r WHERE r."rn" > 1
);--> statement-breakpoint
ALTER TABLE "research_packages" ADD CONSTRAINT "research_packages_job_unique" UNIQUE("job_id");
